### ISSUE TITLE
Create langchain code that will connect with instruct GPT model that will solve your physics problem

### ISSUE THREAD

**Issue by Rami-Ismael** [Rami-Ismael/physics_qa_llm#4]
# The Pros of LangChain
1. Large language models (LLMs) are emerging as a transformative technology, enabling developers to build applications they previously could not. But more than using these LLMs in isolation is needed to create a compelling app - the real power comes when you combine them with other sources of computation or knowledge. Enhance the ability the prompt
2. The abstraction of the problem is shallow, making it easy to contribute and edit codes.
# ToDo
- [ ] Create an environment files 
- [ ] Create a requirement python library files 
```
pip freeze > requirement.txt
```
- [ ] Create a prompt template 
- [ ] Upload two vector databases with an example that has a chain of thought of example or. Not this will be called an ablation study 
- [ ] Ask if there is an example of using a text splitter
- [ ] [[Data Augmented Generation]]
- [ ] Go through Question Answering LLM model
